import * as React from "react";
import Layout from "@/layout/layout";
import Head from "next/head";
import { Box, Container } from "@mui/material";
import { NextPageWithLayout } from "../_app";

const OpenGraphPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Open Graph - Semantic HTML</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:image" content="<generated>" />
        <meta property="og:image:type" content="<generated>" />
        <meta property="og:image:width" content="<generated>" />
        <meta property="og:image:height" content="<generated>" />
      </Head>

      <Box component={"section"}>
        <Container maxWidth={false}>Open Graph Image Section Added</Container>
      </Box>
    </>
  );
};

OpenGraphPage.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
};

export default OpenGraphPage;
