import * as React from "react";
import Layout from "@/layout/layout";
import Head from "next/head";
import { Box, Container } from "@mui/material";
import { NextPageWithLayout } from "../_app";

const OpenGraphPage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Open Graph - Semantic HTML</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="Open Graph" />
        <meta
          property="og:image"
          content="https://images.creativefabrica.com/products/previews/2023/11/03/ryt9zIRo3/2XfkZBs7iIPfUjxeQDSv4o3ljd3-desktop.jpg"
        />
        <meta property="og:image:type" content="image/jpg" />
        <meta property="og:image:width" content="200" />
        <meta property="og:image:height" content="160" />
        <meta property="og:image:alt" content="About Flowers" />
      </Head>

      <Box component={"section"}>
        <Container maxWidth={false}>Open Graph Image Section Added</Container>
      </Box>
    </>
  );
};

OpenGraphPage.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
};

export default OpenGraphPage;
