import * as React from "react";
import { NextPageWithLayout } from "./_app";
import Layout from "@/layout/layout";
import Head from "next/head";
import { Box, Container } from "@mui/material";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Semantic HTML</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component={"section"}>
        <Container maxWidth={false}>Section 1</Container>
      </Box>
    </>
  );
};

Home.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
